GET http://localhost:3000/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiS2FzaEB0ZXN0MTIzNC5jb20ifSwiaWF0IjoxNjEwNzY0NjA0LCJleHAiOjE2MTExMjQ2MDR9.mtFqoloeyD8cXlh-TClKeHl4-KU0GxZnHpAx18lMeQA

###

POST  http://localhost:3000/auth/login
Content-Type:application/json

{
    "password": "test123",
    "email": "Kash@test1234.com"  
}

###

POST  http://localhost:3000/auth/token
Content-Type:application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiS2FzaEB0ZXN0MTIzNC5jb20ifSwiaWF0IjoxNjEwNzY0NjA0fQ.yhc92tGOQfWDR2u0kWAMMGcqTxf9dJ6cSjRbXAh2GKI",
    "id": "Kash@test1234.com"
}

###

POST  http://localhost:3000/auth/register
Content-Type:application/json

{
    "username": "Kash",
    "password": "test123",
    "passwordConfirm":"test123",  
    "email": "Kash@test1234.com"  
}